route:
  group_by: ['alertname', 'cluster', 'service']
  # If an alert isn't caught by a route, send it slack.
  receiver: slack_general
  routes:
    # Send severity=slack alerts to slack.
    - match:
        severity: slack
      receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#general'
